# Generated by Django 5.2.14 on 2026-05-26 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Export'), ('UTILITY', 'Utility Electricity'), ('TRAVEL', 'Corporate Travel')], max_length=20)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Purchased Electricity'), ('SCOPE_3', 'Scope 3 - Value Chain')], max_length=10)),
                ('category', models.CharField(max_length=255)),
                ('activity_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('supplier_vendor', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_manually_edited', models.BooleanField(default=False)),
                ('edit_notes', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='normalized_records', to='organizations.organization')),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
    ]
