# Generated by Django 5.2.14 on 2026-05-26 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0002_initial'),
        ('ingestion', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalystFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flags_raised', to=settings.AUTH_USER_MODEL)),
                ('normalized_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='emissions.normalizedrecord')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flags_resolved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('INGESTED', 'Data Ingested'), ('FLAGGED', 'Record Flagged'), ('EDITED', 'Record Manually Edited'), ('APPROVED', 'Record Approved'), ('REJECTED', 'Record Rejected'), ('FLAG_RESOLVED', 'Flag Resolved')], max_length=20)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='ingestion.ingestionrun')),
                ('normalized_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='emissions.normalizedrecord')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='organizations.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
